### ISSUE TITLE
Does it have a database of crops used for crop rotation?

### ISSUE THREAD

**Issue by rugk** [chrispahm/fruchtfolge#1]
Does it have a database used to determine, which crops may/are used for crop rotation? The reason is that we could need that data for another project: See https://github.com/rugk/crops-parser. Or rather we need to know, which crops are *certainly not* used for crop rotation. :smiley: 

As you also use OSM here, I think our project could (indirectly) help you. :wink: 

/cc @westnordost

**Comment by chrispahm** [comment]
Thanks for your comment. Indeed your project looks really interesting, too!  
As you may have seen in the code, there is a CouchDB database attached to the Web app. We currently can't share all parts of it as the project is not advanced enough, but I attached the .json file including the crop rotations settings for you. These were taken from the [Chamber of Agriculture NRW](https://www.landwirtschaftskammer.de/landwirtschaft/ackerbau/fruchtfolge/tabellen-fruchtfolge-pdf.pdf) and [Freyer (2003)](https://www.amazon.de/Fruchtfolgen-Bernhard-Freyer/dp/3800135760).  
A problem you may run into is that the crop names are in German, and follow the codes used internally by the Chamber of Agriculture.  
Let me know if you need anything else! If you're interested, you may also want to have a look at this study [Schönart et al. (2009)](https://wpr.boku.ac.at/wpr_dp/DP-45-2009.pdf)


[crop_recommendations.json.zip](https://github.com/Toffi-123/fruchtfolge/files/1141955/crop_recommendations.json.zip)

**Comment by rugk** [comment]
Thanks for your reply, the JSON is indeed interesting. For now, we've manually managed/edited the list, but maybe we come back to it later.

**Comment by chrispahm** [comment]
Ok, just for the sake of it, I'll leave a short explanation of the JSON file as I just realised how it is not intuitive right away

```json
...
  "Winterweizen": {
  	"rotBreak": 2,
  	"subseqCrops": [
  		"Wintergerste",
  		"Möhre",
  		"Sommergerste",
  		"Raps",
  		"Zuckerrüben",
  		"Acker-/Puff-/Pferdebohne",
  		"Kartoffeln",
  		"Mais",
  		"Zwiebeln",
  		"Erbsen"
  	],
  	"rootCrop": false,
  	"leguminosae": false,
  	"quality": 35,
  	"maxShare": 0.33,
  	"efaFactor": 0
  },
...
```  
```rotBreak``` Defines the amount of years the crop has to be paused growing on a plot (rotation break)  
```subseqCrops``` An array defining (almost) all possible subsequent crops -> this is NOT sorted by any means of likelihood or recommendation  
```rootCrop``` Boolean that is true for crops that need "picking" of the soil (German: Hackfrüchte)  
```leguminosae``` Boolean that is true if the crop is a legume  
```quality``` Minimum required soil quality, expressed as a Muencheberg Soil Quality Rating score  
```maxShare``` Maximum growing share of that crop of overall crop share  
```efaFactor``` Factor assigned to the crop in the EU Greening directive for fulfilling the greening obligations
